FROM maven:3.9.0 eclipse-temurin:17-jdk-alpine as build
                 VOLUME /tmp
                 COPY target/*.jar app.jar
                 ENTRYPOINT ["java","-jar","/app.jar"]
                 EXPOSE 7009rin:17-jdk-alpine

COPY --from=build  /target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 7009