FROM maven:3.8.2-jdk-11 AS build
COPY . .
RUN mvn clean package -Pprod -DskipTests


FROM openJdk:11-jdk-slim
COPY --from=build  /target/vendor.jar vms.jar
EXPOSE 7009
ENTRYPOINT ["java","-jar","/vms.jar"]