FROM ubuntu:latest AS build
RUN ap-get update
RUN ap-get install opendjdk-1.8-jdk -y
COPY . .

FROM openjdk:17-jdk-slim
EXPOSE 8080
COPY --from=build /target/*.jar vendor.jar

ENTRYPOINT ["java","-jar","/vendor-0.0.1.jar"]